version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - sqlite_data:/app/data
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped

volumes:
  sqlite_data: 